"""Update user models with alumni status and drop alumni table

Revision ID: bc6122ab0493
Revises: b7dafffde0a0
Create Date: 2025-10-04 02:27:01.778844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc6122ab0493'
down_revision: Union[str, Sequence[str], None] = 'b7dafffde0a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alumni')
    op.add_column('coaches', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('coaches', sa.Column('is_alumni', sa.Boolean(), nullable=True))
    op.add_column('coaches', sa.Column('last_active_at', sa.DateTime(), nullable=True))
    op.add_column('student_athletes', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('student_athletes', sa.Column('is_alumni', sa.Boolean(), nullable=True))
    op.add_column('student_athletes', sa.Column('last_active_at', sa.DateTime(), nullable=True))
    op.add_column('teams', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('teams', sa.Column('is_alumni', sa.Boolean(), nullable=True))
    op.add_column('teams', sa.Column('last_active_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'last_active_at')
    op.drop_column('teams', 'is_alumni')
    op.drop_column('teams', 'is_active')
    op.drop_column('student_athletes', 'last_active_at')
    op.drop_column('student_athletes', 'is_alumni')
    op.drop_column('student_athletes', 'is_active')
    op.drop_column('coaches', 'last_active_at')
    op.drop_column('coaches', 'is_alumni')
    op.drop_column('coaches', 'is_active')
    op.create_table('alumni',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('interests', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('location', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('linkedin', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('alumni_pkey'))
    )
    # ### end Alembic commands ###
