"""add conversations+messaging for thread and direct + connect child to Team Impact

Revision ID: e916d84aba96
Revises: 9a3b124b43b1
Create Date: 2025-10-04 02:06:20.834019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e916d84aba96'
down_revision: Union[str, Sequence[str], None] = '9a3b124b43b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
